spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 8.142.116.190:8848
    gateway:
      routes:
        - id: baidu_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: github_route
          uri: https://www.github.com
          predicates:
            - Query=url,github

        - id: third_party_route
          uri: lb://mall-third-part
          predicates:
            - Path=/api/third-party/**
          filters:
            - RewritePath=/api/third-party/(?<segment>.*),/$\{segment}
server:
  port: 88
